version: '3.2'

services:
  development:
    image: node:12
    stdin_open: true
    volumes:
      - .:/home/node/app:cached
    working_dir: /home/node/app
    ports:
      - 9009:9009
    entrypoint:
      - yarn
      - storybook
    environment:
      HOST: '0.0.0.0'
