# This workflow automatically deploy our static Storybook to GitHub Pages with each and every commit to 'base'

name: Storybook Deploy to GitHub Pages

on:
  push:
    branches:
      - fix-storybook-github-action

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn run deploy-storybook